title: Clients
modelClass: Norotaro\Guardian\Models\Client
list: $/norotaro/guardian/models/client/columns.yaml
recordUrl: 'norotaro/guardian/clients/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
