# ===================================
#  Relation Behavior Config
# ===================================

codes:
  label: "norotaro.guardian::lang.authcode.s_name"
  manage:
    form: $/norotaro/guardian/models/authcode/fields.yaml
  view:
    list: $/norotaro/guardian/models/authcode/columns.yaml
    toolbarButtons: create|delete
